# Generated by Django 4.1.7 on 2023-03-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
