# Generated by Django 4.1.7 on 2023-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.TimeField(),
        ),
    ]
