# Generated by Django 4.1.7 on 2023-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll', '0007_alter_attendance_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DurationField(),
        ),
    ]
