# Generated by Django 4.1.7 on 2023-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll', '0009_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
