# Generated by Django 4.1.7 on 2023-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll', '0010_payroll_status_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
